# Generated by Django 3.2.13 on 2023-02-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='images/default_pic.jpg', upload_to='images/profile_pictures'),
        ),
    ]
