# Generated by Django 3.2.13 on 2023-03-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='images/profile_pictures/default_pic.jpg', upload_to='images/profile_pictures'),
        ),
    ]
